#include "platform.h"

#define BLUE_LED_PIN GPIO_PIN_C8
#define GREEN_LED_PIN GPIO_PIN_C9

#define USART_TX_PIN GPIO_PIN_A9
#define USART_RX_PIN GPIO_PIN_A10

#define BUTTON_PIN GPIO_PIN_A0

#define AM2302_PIN GPIO_PIN_C10
